#!/bin/bash

version=2022.5.3
#Release Version

#Copy logo to $HOME
wget -O LineRiderLogo.png https://raw.githubusercontent.com/Sussy-OS/LRA-Community-Edition/linux/Logo.png

#Install dependincies
sudo apt install -y apt-transport-https dirmngr gnupg ffmpeg mono-devel unzip zip

mkdir -p ~/LineRider
cd ~/LineRider

#Download LRA-Community-Edition build from repo
wget -O linerider.zip https://github.com/Sussy-OS/LRA-Community-Edition/releases/download/${version}/LineRider.game.auto-release.${version}-LR.zip

#Install
unzip linerider.zip
rm linerider.zip

#Add system ffmpeg to expected location
mkdir -p ~/Documents/LRA/ffmpeg/linux
cp $(command -v ffmpeg) ~/Documents/LRA/ffmpeg/linux/ffmpeg

#Menu shortcut
echo "[Desktop Entry]
Name=LineRider
Comment=An Open Source spiritual successor to the flash game Line Rider
Icon=$HOME/LineRiderLogo.png
Exec=mono $HOME/LineRider/linerider.exe
Path=$HOME/LineRider/
Type=Application
Terminal=false
Categories=Game;" > ~/.local/share/applications/LineRider.desktop

echo "Installed LineRider!"
