name: Build When Push
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[10.0.40219.1,16.0.30114.105]'
      - name: Build app for release
        run: msbuild src\linerider.sln -t:rebuild -verbosity:diag -property:Configuration=Release
