name: Create Release

on: workflow_dispatch

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: download workflow artifact
        uses: benday-inc/download-latest-artifact@main
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository_owner: 'Sussy-OS'
          repository_name: 'LRA-Community-Edition'
          workflow_name: 'Build LineRider'
          branch_name: 'linux'
          artifact_name: 'linerider'
          download_path: '${{ github.workspace }}'
          download_filename: 'linerider.zip'
          
      - name: get tag
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.GIT_TAG_NAME }}.0
          release_name: Release ${{ env.GIT_TAG_NAME }}.0
          body: |
            LineRider auto-release
          draft: false
          prerelease: false
          
      - uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.zip"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
          draft: false
