name: Create Release

on: workflow_dispatch

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
          
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: calver
          increment: patch
        
      - name: Make Changelog
        uses: johnyherangi/create-release-notes@v1.0.3
        id: create-release-notes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: LineRider game auto-release ${{ steps.version.outputs.version }}
          body: |
            LineRider auto-release ${{ steps.version.outputs.version }}. Get it on Pi-Apps!
            
            If you would like to update your build of LineRider, either wait for Pi-Apps to do it, or run this command in your HOME directory:
            ```
            rm -rf LineRider && sudo rm -rf /opt/LineRider && sudo mkdir /opt/LineRider && cd /opt/LineRider && sudo wget -O linerider.zip "https://github.com/Sussy-OS/LRA-Community-Edition/releases/download/${{ steps.version.outputs.version }}/LineRider.game.auto-release.${{ steps.version.outputs.version }}-LR.zip" && sudo unzip linerider.zip && sudo rm linerider.zip
            ```

              ## Changelog:
              
            ${{ steps.create-release-notes.outputs.release-notes }}
            
          draft: false
          prerelease: false
          
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: Upload Files
          token: ${{ secrets.PERSONAL_TOKEN }}
