name: Create Release

on: workflow_dispatch

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: download workflow artifact
        uses: benday-inc/download-latest-artifact@main
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository_owner: 'Sussy-OS'
          repository_name: 'LRA-Community-Edition'
          workflow_name: 'Build LineRider'
          branch_name: 'linux'
          artifact_name: 'linerider'
          download_path: '${{ github.workspace }}'
          download_filename: 'linerider.zip'
          
      - uses: wemogy/next-version-action@2.0.1
        id: release-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projects: 'Single'
          prefix: ''
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.release-version.outputs.next-version }}
          release_name: LineRider game auto-release ${{ steps.release-version.outputs.next-version }}
          body: |
            LineRider auto-release. Get it on Pi-Apps!
            ${{ steps.versioning.outputs.changelog }}
          draft: false
          prerelease: false
          
      - uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.zip"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
          draft: false
