name: Create Release

on: workflow_dispatch

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Get next version
        uses: reecetech/version-increment@2022.2.5
        id: version
        with:
          scheme: calver
          increment: patch
          
      - name: Make Changelog
        id: changelog
        uses: gandarez/changelog-action@v1.0.4   
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: LineRider game auto-release ${{ steps.version.outputs.version }}
          body: |
            LineRider auto-release ${{ steps.version.outputs.version }}. Get it on Pi-Apps!
              Changelog:
              
            ${{ steps.changelog.outputs.changelog }}
            
          draft: false
          prerelease: false
          
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Upload Files
          token: ${{ secrets.PERSONAL_TOKEN }}
