name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  # can be used to run workflow manually
  workflow_dispatch:
  schedule:
    # Automatically run on every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          # Access token with `workflow` scope is required
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.4
        with:
          # Optional, This will be used to configure git
          # defaults to `github-actions[bot]` if not provided


          # Optional, allows customizing the commit message and pull request title
          # Both default to 'Update GitHub Action Versions'


          # Access token with `workflow` scope is required
          token: ${{ secrets.PERSONAL_TOKEN }}
          # Do not update these actions (Optional)
          # You need to add JSON array inside a string
          # because GitHub Actions does not yet allow `Lists` as input
