name: Update Version Files

on:
  push:
    branches: [ linux ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        
    - name: Get next version
      uses: reecetech/version-increment@2024.4.4
      id: version
      with:
        scheme: calver
        increment: patch
          
    - name: Edit version file
      run: sed -i '1 c\${{ steps.version.outputs.version }}' version
      
    - name: Edit src/Program.cs file
      run: sed -i '39 c\        public static string Version = "${{ steps.version.outputs.version }}";' src/Program.cs
      
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: linux
        
    - name: Invoke workflow without inputs
      uses: benc-uk/workflow-dispatch@v1.2.3
      with:
        workflow: Build LineRider
        token: ${{ secrets.PERSONAL_TOKEN }}
